version: '3.8'

services:
  mysql:
    image: mysql:8.0.43  # Certifique-se de usar a versão correta do MySQL
    container_name: mysql1
    environment:
      MYSQL_DATABASE: futurestack
      MYSQL_USER: futurestack
      MYSQL_PASSWORD: futurestack
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3307:3306"  # Mapeando a porta 3306 do container para 3307 no host
    volumes:
      - mysql-data:/var/lib/mysql  # Volume persistente para os dados do MySQL
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin -u root -prootpassword ping"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/futurestack
      SPRING_DATASOURCE_USERNAME: futurestack
      SPRING_DATASOURCE_PASSWORD: futurestack
    depends_on:
      - mysql

volumes:
  mysql-data:
